### PR TITLE
Fix race conditions with asynchronous cache stores

### PR DESCRIPTION
**Pull request by aldesantis**

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
Thanks @aldesantis ! I would merge this, just want to wait for @brchristian opinion here.

**Review by brchristian — CHANGES_REQUESTED** [review]
Why did you remove the comment in line 46?

**Comment by brchristian** [comment]
Hi @aldesantis thanks for taking a look at this. I’m not actually certain that the PR as submitted will prevent race conditions if the cache entry is `nil`, it enters the code below... Is this not the same thing that will happen with the `fetch...do` block?

(Also, why is the 30 minute expiry removed?)

I see that rails comes with a `race_condition_ttl` - why should we not simply use that?

More broadly, I’m not actually very worried about race conditions here. The fetch is already dependent on the user and order... So we’ll only get race conditions, I believe, if the user themselves is checking out in multiple browser tabs with the same cart contents. Is that really a concern worth architecting around? My feeling is no, but feel free to convince me!

A separate point, but I see we are using `time_to_idle`. This may be old syntax...I wonder if simply using `expires_in` is better.

**Comment by aldesantis** [comment]
@brchristian sorry, I didn't explain this in the PR, but actually this is happening in production with Memcached for us. `tax_for_item` returns `nil` in some instances and eventually we found out that it's happening because of the way the caching works. I'm not sure whether it's actually a race condition or not, but there's something about that `Rails.cache.fetch` block that is causing the cache to fail randomly for us, while this solution stabilizes it.

The race condition could be due to the fact that the previous implementation writes and then immediately reads from the cache, possibly when the operation was not persisted yet. It's also possible for the write to fail for a number of other reasons - in this case, the implementation would be completely broken. If you look at the commit message, problem and solution are also explained there.

I removed the comment by mistake, I'll put it back in. Regarding the expiry, I removed it because `fetch` written that way is just reading, not also writing, so the expiry would never be used even if it was specified. In fact, `fetch` can be replaced with `read` now, which I just did. :)

**Comment by brchristian** [comment]
Hi @aldesantis it’s possible I’m confused here. As far as I can see, the existing code uses the `fetch` method exactly as it’s designed to be used.

See the Rails documentation [here](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch):

`If there is no such data in the cache (a cache miss), then nil will be returned. However, if a block has been passed, that block will be passed the key and executed in the event of a cache miss. The return value of the block will be written to the cache under the given cache key, and that return value will be returned.`

Unless there is a syntax error or typo in the current code, I’m not seeing anything that leads me to your conclusion that "`fetch` written that way is just reading, not also writing".

It seems to me that if you’re seeing race condition issues with `Rails.cache.fetch` that this would be a Rails issue, not a `solidus_tax_cloud` issue, as (again correct me if I’m wrong) the extension is using `Rails.cache.fetch` as it is intended to be used. Namely, it reads if the value is present, and executes/writes/returns if the value is not present.

**Comment by aldesantis** [comment]
@brchristian sorry, I think I'm failing to explain the situation properly here.

The _syntax_ of the `fetch` method call is correct. The problem is what happens _inside_ the block passed to the `fetch` method: you're not simply returning a value, but first writing a value to the same key you're passing to `fetch` and then reading it back from the cache immediately afterwards. To simplify, it's something like the following code example:

```ruby
Rails.cache.fetch('my-cache-key') do
  Rails.cache.write 'my-cache-key', 'cache-value'
  Rails.cache.read 'my-cache-key'
end
```

This is a very unusual way to use `fetch`, which is normally used in this way instead:

```ruby
Rails.cache.fetch('my-cache-key') do
  'cache-value'
end
```

I have two theories on why the current implementation breaks randomly:

- Theory 1: it's because using `fetch` in this way throws off Rails for some reason and creates a race condition or another inconsistency in the Ruby/Rails code itself.
- Theory 2: it's because a race condition is happening in the cache store. That is, since `put()` is asynchronous in Memcached, the value has not been persisted yet at the time it's read back from the cache and `Rails.cache.read` returns `nil`. This would also cause the value to _never_ be persisted to the cache, because `fetch` will overwrite whatever value is _eventually_ written to the cache (via `Rails.cache.write`) with the `nil` value returned by the block.

To be honest, I'm not sure what the problem is between these two. For us, it started happening with the upgrade to Solidus 2.7 and Rails 5.2 (we also upgraded this gem of course). The patch I submitted seems to fix the problem, whatever it is, because it alters the `fetch` block to just return a value from memory instead of reading back from the cache.

Let me know if this is clearer or if you need more information!

**Comment by aldesantis** [comment]
@kennyadsl @brchristian I have updated the implementation slightly to also work with shipments. You may want to take another look.

**Comment by brchristian** [comment]
Thank you for clarifying that! I believe I am now seeing the issue as you describe. My hunch, like yours, is that the race condition does indeed have to do with the final `cache.read` at the end.

It seems to me that the minimum viable fix would be something like simply changing the final

```ruby
Rails.cache.read(['TaxCloudRatesForItem', item.tax_cloud_cache_key], version: item.tax_cloud_cache_version)
```

to

```ruby
item_tax_amount
```

and including the relevant `item_tax_amount` code above, obviously, to assign that variable appropriately.

My sense is that if we did this, we don’t need to also make the change with

```ruby
      cached_value = Rails.cache.read(
        ['TaxCloudRatesForItem', item.tax_cloud_cache_key],
        version: item.tax_cloud_cache_version,
      )

      return cached_value if cached_value

      . . .
```

because unless I’m mistaken, that’s exactly how `cache.fetch` works when you pass a block. If the cache hits, it returns that, otherwise it proceeds.

I’d also like to keep the PRs as clean as possible, so would love to see shifting from `time_to_idle` to `expires_in` if we want to (and actually I think there are good concurrency reasons _not_ to make this change), or improving the per-shipment logic, in separate PRs.

If you’re willing to pare this one down just to the `item_tax_amount` changes, I’m quite happy to merge, as I do think that will fix this race condition issue.

**Comment by aldesantis** [comment]
@brchristian I changed this as requested, however note that I still think using `Rails.cache.fetch` and writing to the same cache key you're fetching _inside_ the block is weird behavior that might stop working at some point or may not work at all with certain cache stores.

**Comment by brchristian** [comment]
This is looking really good.

I’m happy to merge as is, but it also occurs to me that if you’re worried about writing to a cache while in the `do` block for fetching that cache (which I admit is a bit weird), what do you think about writing to the cache conditional on the thing _not_ being `item`?

For instance, something like:
```ruby
if shipment == item
  item_tax_amount = tax_amount
else
    Rails.cache.write(
     ['TaxCloudRatesForItem', shipment.tax_cloud_cache_key],
     tax_amount,
     version: shipment.tax_cloud_cache_version,
     time_to_idle: 30.minutes,
   )
end
```

**Comment by aldesantis** [comment]
@brchristian good idea, just updated!

**Review by brchristian — APPROVED** [review]

**Comment by brchristian** [comment]
Looks like we are good on all the Travis builds except `master` because something has changed with the coupon code DOM object. We can deal with that separately. I’m going to merge this. Thank you, @aldesantis! 🎉

**Pull request merged**
