### PR TITLE
Revises tax calculations to account for discounts

### PR DESCRIPTION
**Pull request by rlasch**

### CODE REVIEW

**Comment by rlasch** [comment]
@brchristian This is the follow up to the previous PR.  What I didn't see how to do is to tie a promotion to the shipping costs.  I assume that this is what a promotion is when it's tied to an order and not a line item?

**Comment by jeffreyguenther** [comment]
Is there any interesting in moving this PR forward?

**Comment by brchristian** [comment]
If we can get this rebased onto the current `master` and get the appropriate tests written, I’d very much welcome this functionality.

**Comment by jeffreyguenther** [comment]
Awesome. I'm working on a project that's running into problems with discounted items being charged the wrong tax, so that's great.

I recently pulled down master and ran the test suite and it didn't pass. Do you have any insight why that might be? A `bundle install` does install Solidus 2.6 and Rails 5.2 as they are the latest versions of those libraries. All the `checkout_spec.rb` tests fail. Do you know what the last versions of Solidus and Rails the test suite passed on?

**Comment by brchristian** [comment]
One of the headaches with a sales tax extension is that the sales tax rate can change in any of the 50 US states at basically any time, and then suddenly the test suite is invalid. :-/

Last I checked it was passing in Solidus 2.4 which is what my main project is currently running in production. We are migrating to 2.5 presently so it’s on my list to verify extension capability. I’ll make a note to prioritize the sales tax extension so we can get that straightened out.

**Comment by jeffreyguenther** [comment]
Looks like the issue is due to a whitespace change in Solidus. I'll have a few PRs for small changes to get the test suite back up and running on 2.6.

**Comment by brchristian** [comment]
Whitespace...this is ringing a bell. I know that generally the Solidus team wants compatibility over as many versions of Solidus Core as possible. In that case, I wonder if -- rather than just changing the number of spaces in the spec -- we can change it to a regex that matches any kind of whitespace whatsoever (spaces, tabs, etc.). If so then the test suite for the `master` branch would be green across multiple versions of Solidus -- <= 2.4 and >= 2.5.

**Comment by jeffreyguenther** [comment]
I'm ahead of you 😄 This is what I've done. Separate PRs incoming.

**Comment by brchristian** [comment]
👍

**Comment by brchristian** [comment]
@rlasch I’m currently adding the specs as their own commit, crediting you, then I will look at how best to merge the best of this PR and https://github.com/solidusio-contrib/solidus_tax_cloud/pull/13 to get those specs green.

**Comment by brchristian** [comment]
@rlasch I have merged your work into the current `master`. Thank you!

**Pull request closed without merging**
