### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by aitbw**
This PR aims to get a green Travis build by doing the following:

* Replace `order_coupon_code` -> `coupon_code` (see commit's description for details)
* Gemfile maintenance (see commit's description for details)

It also adds [Solidus v2.8](https://github.com/solidusio/solidus/releases/tag/v2.8.0) to the build matrix :tada:

### CODE REVIEW

**Comment by brchristian** [comment]
@aitbw This looks like terrific work, thank you!

One question – why the change from `github:` to `git:` in the gemfile?

**Comment by aitbw** [comment]
@brchristian So we can fix a Git insecure data fetching warning when running `bundle`

**Comment by brchristian** [comment]
When I look at the "official" Solidus extensions like [solidus_support](https://github.com/solidusio/solidus_support) or [solidus_gateway](https://github.com/solidusio/solidus_gateway) or [solidus_braintree](https://github.com/solidusio/solidus_braintree) or [solidus_auth_devise](https://github.com/solidusio/solidus_auth_devise), I see the standard `github` syntax there. As a general rule, I think that community-supported Solidus extensions should follow the norms and conventions of the official and most popular extensions.

If you can remove that line from this PR, I’m happy to merge the rest of these changes, and then we can open a separate Issue/PR if you want to discuss the best way to deal with the bundler warnings.

**Comment by aitbw** [comment]
@brchristian I understand your concern but in this case I think, we can migrate safely from one kind of syntax to another, as warnings are very annoying.

That said, we've been migrating from `github` to `git` for quite a while now, as you can see [here](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aaitbw+archived%3Afalse+is%3Aclosed+user%3Asolidusio-contrib)

**Comment by brchristian** [comment]
I agree that the warnings are annoying, but can’t you make them go away with `bundle config github.https true`?

**Comment by aitbw** [comment]
That would only fix it for me, and for as long as I don't format my PC.

**Comment by brchristian** [comment]
I think we may have a difference in opinion here. I don’t necessarily think it’s the responsibility of every extension maintainer to enforce https over the git protocol. I see this as really a Bundler issue. Any individual user that doesn’t want the warnings can easily stop them. Furthermore Bundler 2.0 will use https by default. I’m happy to merge all the rest of your changes, and we can continue the conversation about https in a separate PR if you’d like.

**Comment by brchristian** [comment]
Merging now with a (possibly temporary) reversion of the `github:` line. Happy to discuss in a separate PR!

Thank you for all of the hard work that went into this PR. It’s great to have the specs green and everything running smoothly in Solidus 2.8! 👍

**Pull request merged**
