### PR TITLE
Revises tax calculations to account for discounts

### PR DESCRIPTION
**Pull request by jeffreyguenther**

### CODE REVIEW

**Comment by jeffreyguenther** [comment]
@brchristian and @alepore, can you review this work?

**Comment by brchristian** [comment]
No problem to have a look. I’m going to try to get the 2.6 specs green first before adding features. Will try to have a look at this PR later this week.

As a side note, there is a lot of good work in here that I’d be happy to merge as their own PRs, and would prefer to do so rather than a big PR with many commits. For instance, I’d be happy to merge https://github.com/solidusio-contrib/solidus_tax_cloud/pull/13/commits/7fee7501eee233e5a24cfa1fd3ffccb6ddb28de0 as its own PR and also https://github.com/solidusio-contrib/solidus_tax_cloud/pull/13/commits/7fc1122881a0aeb5ac0a01f63731efb8bad53e90 and https://github.com/solidusio-contrib/solidus_tax_cloud/pull/13/commits/b23601870cb65b1f5335a2c5e94f078574f006d0 as their own PRs.

Lastly, I’m somewhat skeptical of https://github.com/solidusio-contrib/solidus_tax_cloud/pull/13/commits/059c4cee5491714aa17b1578da3e10fac077725f and https://github.com/solidusio-contrib/solidus_tax_cloud/pull/13/commits/f0ef338d105aa839a4ab9c993f619a77f7f37415 because the last I checked (earlier this week), our specs were green in 2.4 and 2.5.

**Comment by jeffreyguenther** [comment]
I might be missing something..., but all the code in this PR is new (via rlasch's branch) or added by me. 059c4ce and f0ef338 clean up the code that was introduced in 60a6584. Making separate PRs for the other small cleanups doesn't really make sense outside the context of this work as they only affect this work.

I believe you've already merged PRs that cleaned up the whitespace issues and a couple other things in master that were preventing the tests from passing.

If there's one thing I think we should do before merging this PR, it's to update the Travis/Gemfile/gemspec so that when tests run on master, we can see how the tests run for all the versions of Solidus that master is supposed to support. I can work on that this afternoon building off the work done in [travis](https://github.com/solidusio-contrib/solidus_tax_cloud/tree/travis).

**Comment by brchristian** [comment]
Okay, got it. That makes sense. Let’s loop back on this and take a closer look once we (1) get the `travis` branch merged, and (2) get the 2.6 specs green.

**Comment by alepore** [comment]
👍 looks good!
is `Shipment#price_with_discounts` used somewhere?

**Comment by brchristian** [comment]
@jeffreyguenther This is terrific work. Merged! Thank you!

**Comment by brchristian** [comment]
@jeffreyguenther Quick follow-up that I’ve had to be slightly fancy to get the shipping promotion specs passing in more recent versions of Solidus, because they do something tricky with the way the AJAX refreshes the page. See https://github.com/solidusio-contrib/solidus_tax_cloud/commit/2c53a13e2d6af4ce011723cb4aa0a07bad55ac5c. However this is a bit finnicky and one of the Travis builds (Solidus 2.5 + MySQL) doesn’t seem to like it. Let me know if you know a cleaner way; PRs welcome. 🍻

**Pull request merged**
