### PR TITLE
rename solidus_extension_dev_tools -> solidus_dev_support

### PR DESCRIPTION
**Pull request by brchristian**

### CODE REVIEW

**Comment by brchristian** [comment]
I suspect this will resolve https://github.com/solidusio-contrib/solidus_tax_cloud/issues/29

**Comment by aldesantis** [comment]
@brchristian thanks! You should also remove it from the Gemfile.

**Comment by aldesantis** [comment]
@brchristian you'll need to add solidus_support as an additional dependency, it was removed as a dependency from solidus_dev_support.

**Comment by aldesantis** [comment]
@brchristian thanks, looks like we have some other failures now, not sure what they're about exactly.

**Comment by brchristian** [comment]
@aldesantis Looks like specs are now passing.

**Review by aldesantis — APPROVED** [review]

**Pull request merged**
